# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install catboost
!pip install lightgbm

from sklearn.datasets import fetch_california_housing
import pandas as pd

housing = fetch_california_housing(as_frame=True)
df = housing.frame

print(df.info())
print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score


X = df.drop(columns=['MedHouseVal'])
y = df['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Средняя ошибка (MAE): ${mae * 100000:.0f}")
print(f"Точность модели (R^2 Score): {r2 * 100:.1f}%")

import numpy as np


SF_LAT, SF_LON = 37.7749, -122.4194
df_geo = df.copy()


df_geo['Dist_to_SF'] = np.sqrt((df_geo['Latitude'] - SF_LAT)**2 + (df_geo['Longitude'] - SF_LON)**2)


X_geo = df_geo.drop(columns=['MedHouseVal'])
y_geo = df_geo['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X_geo, y_geo, test_size=0.2, random_state=42)

model_geo = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model_geo.fit(X_train, y_train)

y_pred_geo = model_geo.predict(X_test)

mae_geo = mean_absolute_error(y_test, y_pred_geo)
r2_geo = r2_score(y_test, y_pred_geo)

print(f"ОШИБКА С РАССТОЯНИЕМ ДО СФ (MAE): ${mae_geo * 100000:.0f}")
print(f"ТОЧНОСТЬ С РАССТОЯНИЕМ ДО СФ (R^2): {r2_geo * 100:.1f}%")

from catboost import CatBoostRegressor

model_cat = CatBoostRegressor(iterations=1000, learning_rate=0.05, verbose=100, random_seed=42)

model_cat.fit(X_train, y_train)

y_pred_cat = model_cat.predict(X_test)

mae_cat = mean_absolute_error(y_test, y_pred_cat)
r2_cat = r2_score(y_test, y_pred_cat)

print("\n--- СРАВНЕНИЕ РЕЗУЛЬТАТОВ ---")
print(f"RandomForest + Dist_to_SF: MAE ${mae_geo * 100000:.0f} | R2 {r2_geo * 100:.1f}%")
print(f"CatBoost + Dist_to_SF:     MAE ${mae_cat * 100000:.0f} | R2 {r2_cat * 100:.1f}%")

from xgboost import XGBRegressor

model_xgb = XGBRegressor(n_estimators=1000, learning_rate=0.05, random_state=42, n_jobs=-1)
model_xgb.fit(X_train, y_train)

y_pred_xgb = model_xgb.predict(X_test)

mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)

print("--- ИТОГОВОЕ СРАВНЕНИЕ ВСЕХ 3-х МОДЕЛЕЙ ---")
print(f"1. RandomForest: MAE ${mae_geo * 100000:.0f} | R2 {r2_geo * 100:.1f}%")
print(f"2. XGBoost:      MAE ${mae_xgb * 100000:.0f} | R2 {r2_xgb * 100:.1f}%")
print(f"3. CatBoost:     MAE ${mae_cat * 100000:.0f} | R2 {r2_cat * 100:.1f}%")

import pandas as pd
import matplotlib.pyplot as plt

importance = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)

print("Важность признаков:")
print(importance)

import plotly.express as px

test_df = X_test.copy()
test_df['Real_Price'] = y_test * 100000
test_df['Predicted_Price'] = y_pred * 100000
test_df['Error'] = abs(test_df['Real_Price'] - test_df['Predicted_Price'])

fig = px.scatter_mapbox(
    test_df,
    lat='Latitude',
    lon='Longitude',
    color='Predicted_Price',
    size='Population',
    color_continuous_scale='Jet',
    size_max=15,
    zoom=5,
    hover_name='Real_Price',
    hover_data=['Predicted_Price', 'Error', 'MedInc'],
    title='Предсказанная стоимость жилья на карте Калифорнии'
)


fig.update_layout(mapbox_style="open-street-map")
fig.show()

import numpy as np


LA_LAT, LA_LON = 34.0522, -118.2437
SD_LAT, SD_LON = 32.7157, -117.1611
SJ_LAT, SJ_LON = 37.3382, -121.8863

df_pro = df.copy()


df_pro['Dist_to_SF'] = np.sqrt((df_pro['Latitude'] - 37.7749)**2 + (df_pro['Longitude'] - -122.4194)**2)
df_pro['Dist_to_LA'] = np.sqrt((df_pro['Latitude'] - LA_LAT)**2 + (df_pro['Longitude'] - LA_LON)**2)
df_pro['Dist_to_SD'] = np.sqrt((df_pro['Latitude'] - SD_LAT)**2 + (df_pro['Longitude'] - SD_LON)**2)
df_pro['Dist_to_SJ'] = np.sqrt((df_pro['Latitude'] - SJ_LAT)**2 + (df_pro['Longitude'] - SJ_LON)**2)

df_pro['Min_Dist_to_City'] = df_pro[['Dist_to_SF', 'Dist_to_LA', 'Dist_to_SD', 'Dist_to_SJ']].min(axis=1)


df_pro['Bedrooms_Ratio'] = df_pro['AveBedrms'] / df_pro['AveRooms']
df_pro['People_Per_Room'] = df_pro['Population'] / df_pro['AveRooms']

from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

X_pro = df_pro.drop(columns=['MedHouseVal'])
y_pro = df_pro['MedHouseVal']


X_tr, X_te, y_tr, y_te = train_test_split(X_pro, y_pro, test_size=0.2, random_state=42)


model_xgb_tuned = XGBRegressor(
    n_estimators=2000,
    learning_rate=0.02,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)
model_xgb_tuned.fit(X_tr, y_tr)
y_pred_xgb_pro = model_xgb_tuned.predict(X_te)


model_cat_pro = CatBoostRegressor(iterations=2000, learning_rate=0.03, depth=7, verbose=0, random_seed=42)
model_cat_pro.fit(X_tr, y_tr)
y_pred_cat_pro = model_cat_pro.predict(X_te)

y_pred_ensemble = (y_pred_xgb_pro + y_pred_cat_pro) / 2

r2_ens = r2_score(y_te, y_pred_ensemble)
mae_ens = mean_absolute_error(y_te, y_pred_ensemble)

print("--- РЕЗУЛЬТАТ ПРОДВИНУТОЙ СБОРКИ ---")
print(f"Новая средняя ошибка (MAE): ${mae_ens * 100000:.0f}")
print(f"Новая точность (R2 Score): {r2_ens * 100:.2f}%")

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, r2_score

df_max = df.copy()

df_max = df_max[(df_max['AveRooms'] < 15) & (df_max['AveOccup'] < 6) & (df_max['AveBedrms'] < 5)]

df_max['Dist_to_Coast'] = np.abs(df_max['Longitude'] + df_max['Latitude'] + 84.5) / np.sqrt(2)

df_max['Dist_to_SF'] = np.sqrt((df_max['Latitude'] - 37.7749)**2 + (df_max['Longitude'] - -122.4194)**2)
df_max['Dist_to_LA'] = np.sqrt((df_max['Latitude'] - 34.0522)**2 + (df_max['Longitude'] - -118.2437)**2)
df_max['Dist_to_SD'] = np.sqrt((df_max['Latitude'] - 32.7157)**2 + (df_max['Longitude'] - -117.1611)**2)
df_max['Dist_to_SJ'] = np.sqrt((df_max['Latitude'] - 37.3382)**2 + (df_max['Longitude'] - -121.8863)**2)

coords = df_max[['Latitude', 'Longitude']]
kmeans = KMeans(n_clusters=20, random_state=42, n_init=10)
df_max['Geo_Cluster'] = kmeans.fit_predict(coords)

df_max['Bedrooms_Ratio'] = df_max['AveBedrms'] / df_max['AveRooms']
df_max['Rooms_Per_Person'] = df_max['AveRooms'] / df_max['AveOccup']


X = df_max.drop(columns=['MedHouseVal'])
y = df_max['MedHouseVal']

X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)

model_xgb = XGBRegressor(n_estimators=2500, learning_rate=0.02, max_depth=8, subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1)
model_xgb.fit(X_tr, y_tr)

model_cat = CatBoostRegressor(iterations=2500, learning_rate=0.03, depth=7, cat_features=['Geo_Cluster'], verbose=0, random_seed=42)
model_cat.fit(X_tr, y_tr)

y_pred_max = (model_xgb.predict(X_te) + model_cat.predict(X_te)) / 2

r2_max = r2_score(y_te, y_pred_max)
mae_max = mean_absolute_error(y_te, y_pred_max)

print("--- ИТОГОВЫЙ РЕЗУЛЬТАТ ---")
print(f"Новая средняя ошибка (MAE): ${mae_max * 100000:.0f}")
print(f"Новая точность (R2 Score): {r2_max * 100:.2f}%")

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error, r2_score


df_fin = df.copy()


df_fin = df_fin[(df_fin['AveRooms'] < 15) & (df_fin['AveOccup'] < 6) & (df_fin['AveBedrms'] < 5)]


df_fin['Dist_to_Coast'] = np.abs(df_fin['Longitude'] + df_fin['Latitude'] + 84.5) / np.sqrt(2)


df_fin['Dist_to_SF'] = np.sqrt((df_fin['Latitude'] - 37.7749)**2 + (df_fin['Longitude'] - -122.4194)**2)
df_fin['Dist_to_LA'] = np.sqrt((df_fin['Latitude'] - 34.0522)**2 + (df_fin['Longitude'] - -118.2437)**2)
df_fin['Dist_to_SD'] = np.sqrt((df_fin['Latitude'] - 32.7157)**2 + (df_fin['Longitude'] - -117.1611)**2)
df_fin['Dist_to_SJ'] = np.sqrt((df_fin['Latitude'] - 37.3382)**2 + (df_fin['Longitude'] - -121.8863)**2)


df_fin['Geo_Grid'] = df_fin['Latitude'].round(1).astype(str) + "_" + df_fin['Longitude'].round(1).astype(str)


kmeans = KMeans(n_clusters=35, random_state=42, n_init=10)
df_fin['Geo_Cluster'] = kmeans.fit_predict(df_fin[['Latitude', 'Longitude']])

df_fin['Bedrooms_Ratio'] = df_fin['AveBedrms'] / df_fin['AveRooms']
df_fin['Rooms_Per_Person'] = df_fin['AveRooms'] / df_fin['AveOccup']


df_fin['Geo_Grid_Code'] = df_fin['Geo_Grid'].astype('category').cat.codes

X = df_fin.drop(columns=['MedHouseVal', 'Geo_Grid'])
y = df_fin['MedHouseVal']

X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)


MIN_PRICE = y.min()
MAX_PRICE = y.max()

model_xgb = XGBRegressor(n_estimators=3000, learning_rate=0.015, max_depth=8, subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1)
model_xgb.fit(X_tr, y_tr)
pred_xgb = model_xgb.predict(X_te)

pred_xgb = np.clip(pred_xgb, MIN_PRICE, MAX_PRICE)


model_cat = CatBoostRegressor(iterations=3000, learning_rate=0.02, depth=7, cat_features=['Geo_Cluster', 'Geo_Grid_Code'], verbose=0, random_seed=42)
model_cat.fit(X_tr, y_tr)
pred_cat = model_cat.predict(X_te)

pred_cat = np.clip(pred_cat, MIN_PRICE, MAX_PRICE)


model_lgb = LGBMRegressor(n_estimators=3000, learning_rate=0.015, num_leaves=63, random_state=42, n_jobs=-1, verbose=-1)
model_lgb.fit(X_tr, y_tr)
pred_lgb = model_lgb.predict(X_te)

pred_lgb = np.clip(pred_lgb, MIN_PRICE, MAX_PRICE)

pred_ensemble_3 = (pred_xgb * 0.4) + (pred_cat * 0.35) + (pred_lgb * 0.25)

pred_ensemble_3 = np.clip(pred_ensemble_3, MIN_PRICE, MAX_PRICE)

r2_fin = r2_score(y_te, pred_ensemble_3)
mae_fin = mean_absolute_error(y_te, pred_ensemble_3)

print("--- РЕЗУЛЬТАТ С КАППИНГОМ НА КАЖДУЮ МОДЕЛЬ ---")
print(f"Финальная ошибка (MAE): ${mae_fin * 100000:.0f}")
print(f"Финальная точность (R2 Score): {r2_fin * 100:.2f}%")

import pandas as pd
from sklearn.metrics import mean_absolute_error, r2_score


pred_xgb_c = np.clip(pred_xgb, 0, 5.0)
pred_cat_c = np.clip(pred_cat, 0, 5.0)
pred_lgb_c = np.clip(pred_lgb, 0, 5.0)


combinations = {
    "Только XGBoost": pred_xgb_c,
    "Только CatBoost": pred_cat_c,
    "Только LightGBM": pred_lgb_c,
    "Пара: XGBoost + CatBoost": (pred_xgb_c * 0.55) + (pred_cat_c * 0.45),
    "Пара: XGBoost + LightGBM": (pred_xgb_c * 0.6) + (pred_lgb_c * 0.4),
    "Пара: CatBoost + LightGBM": (pred_cat_c * 0.55) + (pred_lgb_c * 0.45),
    "Тройной: XGB + Cat + LGB": (pred_xgb_c * 0.4) + (pred_cat_c * 0.35) + (pred_lgb_c * 0.25)
}

results = []
for name, pred in combinations.items():
    r2 = r2_score(y_te, pred)
    mae = mean_absolute_error(y_te, pred)
    results.append({"Комбинация": name, "R2 Score (%)": round(r2 * 100, 2), "MAE ($)": round(mae * 100000, 0)})


results_df = pd.DataFrame(results).sort_values(by="R2 Score (%)", ascending=False).reset_index(drop=True)

print("--- СРАВНЕНИЕ ВСЕХ 7 КОМБИНАЦИЙ И АНСАМБЛЕЙ ---")
display(results_df)

best_combo = results_df.iloc[0]
print(f"\nЛУЧШИЙ: {best_combo['Комбинация']} с точностью R2 = {best_combo['R2 Score (%)']}%!")